"use server";

/* funcion para el paserso de datos llegados de la consulta de persona natural */


export const fn_parserResPn = async (req) => {

    const dataReques = req;
    const dataResponseParser = {};

    dataResponseParser.O_MESSID = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-MESSID')];
    dataResponseParser.O_INDATI = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-INDATI')];
    dataResponseParser.O_IPTRAN = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-IPTRAN')];
    dataResponseParser.O_CODTRA = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CODTRA')];
    dataResponseParser.O_CANAL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CANAL')];
    dataResponseParser.O_CODRES = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CODRES')];
    dataResponseParser.O_MENRES = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-MENRES')];
    dataResponseParser.O_TIPOPR = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TIPOPR')];
    dataResponseParser.O_TIPDOC = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TIPDOC')];
    dataResponseParser.O_NITCLI = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-NITCLI')];
    dataResponseParser.O_LUGEXP = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-LUGEXP')];
    dataResponseParser.O_FECESC = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-FECESC')];
    dataResponseParser.O_PRMAPL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-PRMAPL')];
    dataResponseParser.O_SGDAPL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-SGDAPL')];
    dataResponseParser.O_PRMNOM = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-PRMNOM')];
    dataResponseParser.O_SGDNOM = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-SGDNOM')];
    dataResponseParser.O_FECCON = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-FECCON')];
    dataResponseParser.O_LUGCON = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-LUGCON')];
    dataResponseParser.O_PAISCON = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-PAISCON')];
    dataResponseParser.O_NCIONA1 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-NCIONA1')];
    dataResponseParser.O_NCIONA2 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-NCIONA2')];
    dataResponseParser.O_CODSEX = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CODSEX')];
    dataResponseParser.O_ESTCIV = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-ESTCIV')];
    dataResponseParser.O_INDEST = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-INDEST')];
    dataResponseParser.O_OCUPAC = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-OCUPAC')];
    dataResponseParser.O_DECREN = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-DECREN')];
    dataResponseParser.O_DSCARPG = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-DSCARPG')];
    dataResponseParser.O_ESTRAT = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-ESTRAT')];
    dataResponseParser.O_DIRRES = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-DIRRES')];
    dataResponseParser.O_BARRES = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-BARRES')];
    dataResponseParser.O_CODCRES = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CODCRES')];
    dataResponseParser.O_PAIRES = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-PAIRES')];
    dataResponseParser.O_TELRES = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TELRES')];
    dataResponseParser.O_TELCEL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TELCEL')];
    dataResponseParser.O_DEMAIL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-DEMAIL')];
    dataResponseParser.O_DIRFAM = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-DIRFAM')];
    dataResponseParser.O_BARFAM = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-BARFAM')];
    dataResponseParser.O_CODCFA = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CODCFA')];
    dataResponseParser.O_TELFAM = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TELFAM')];
    dataResponseParser.O_INDCOR = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-INDCOR')];
    dataResponseParser.O_ASOCOR = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-ASOCOR')];
    dataResponseParser.O_AUTMAIL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-AUTMAIL')];
    dataResponseParser.O_AUTCEL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-AUTCEL')];
    dataResponseParser.O_FECUAC = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-FECUAC')];
    dataResponseParser.O_CTIPDOC = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CTIPDOC')];
    dataResponseParser.O_CNITCLI = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CNITCLI')];
    dataResponseParser.O_CPRMAPL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CPRMAPL')];
    dataResponseParser.O_CSGDAPL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CSGDAPL')];
    dataResponseParser.O_CPRMNOM = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CPRMNOM')];
    dataResponseParser.O_CSGDNOM = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CSGDNOM')];
    dataResponseParser.O_CTELCEL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CTELCEL')];
    dataResponseParser.O_NOMREF1 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-NOMREF1')];
    dataResponseParser.O_PARENT = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-PARENT')];
    dataResponseParser.O_TELREF1 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TELREF1')];
    dataResponseParser.O_NOMREF2 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-NOMREF2')];
    dataResponseParser.O_TELREF2 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TELREF2')];
    dataResponseParser.O_NOMEMPN = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-NOMEMPN')];
    dataResponseParser.O_DIREMPN = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-DIREMPN')];
    dataResponseParser.O_CIUEMPN = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CIUEMPN')];
    dataResponseParser.O_TELEMPN = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TELEMPN')];
    dataResponseParser.O_FECINE = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-FECINE')];
    dataResponseParser.O_TIPCON = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TIPCON')];
    dataResponseParser.O_TIPEMP = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TIPEMP')];
    dataResponseParser.O_CODACTA = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CODACTA')];
    dataResponseParser.O_CARGOAC = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CARGOAC')];
    dataResponseParser.O_POSNEG = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-POSNEG')];
    dataResponseParser.O_TACTANIO = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TACTANIO')];
    dataResponseParser.O_TACTMES = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TACTMES')];
    dataResponseParser.O_CIIU = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CIIU')];
    dataResponseParser.O_VLRSDO = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRSDO')];
    dataResponseParser.O_VLRSVAR = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRSVAR')];
    dataResponseParser.O_INGARR = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-INGARR')];
    dataResponseParser.O_VLRRENF = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRRENF')];
    dataResponseParser.O_VLRHON = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRHON')];
    dataResponseParser.O_VLROTRN = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLROTRN')];
    dataResponseParser.O_INGCUAL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-INGCUAL')];
    dataResponseParser.O_TOTING = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TOTING')];
    dataResponseParser.O_VLRARR = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRARR')];
    dataResponseParser.O_VLRGFA = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRGFA')];
    dataResponseParser.O_VLRCCO = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRCCO')];
    dataResponseParser.O_VLRPRE = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRPRE')];
    dataResponseParser.O_VLRDNOM = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRDNOM')];
    dataResponseParser.O_VLRTCRE = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRTCRE')];
    dataResponseParser.O_EGRCUAL = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-EGRCUAL')];
    dataResponseParser.O_TOTEGR = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TOTEGR')];
    dataResponseParser.O_FECDATFIN = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-FECDATFIN')];
    dataResponseParser.O_TOTACT = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TOTACT')];
    dataResponseParser.O_TOTPAS = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TOTPAS')];
    dataResponseParser.O_CODPAT1 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-CODPAT1')];
    dataResponseParser.O_VLRPAT1 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VLRPAT1')];
    dataResponseParser.O_ORIGENF = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-ORIGENF')];
    dataResponseParser.O_REFIEST = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-REFIEST')];
    dataResponseParser.O_PAISEST = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-PAISEST')];
    dataResponseParser.O_TRIBEST = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TRIBEST')];
    dataResponseParser.O_TITUL1 = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-TITUL1')];
    dataResponseParser.O_PARENTCO = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-PARENTCO')];
    dataResponseParser.O_INDHDAT = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-INDHDAT')];
    dataResponseParser.O_OBSERV = Object.values(dataReques)[Object.keys(dataReques).indexOf('O-OBSERV')];
    dataResponseParser.O_AGCVIN = dataReques.hasOwnProperty('O-AGCVIN') ? Object.values(dataReques)[Object.keys(dataReques).indexOf('O-AGCVIN')] : 1;
    dataResponseParser.O_VENANU = dataReques.hasOwnProperty('O-VENANU') ? Object.values(dataReques)[Object.keys(dataReques).indexOf('O-VENANU')] : 0;

    return JSON.stringify(dataResponseParser);

};