/*contentHeader controla los mensajes a mostrar en pantalla y los titulos de las cabeceras */
const USER_SMS_STATUS = Object.freeze({
    TITLELOGIN: 'Acceso',
    TITLEPERFIL: 'Seleciona el Perfil',
    PARRAFOHEADERLOGIN: 'Incrementa la rentabilidad, la profundización y la experiencia de tus asociados y clientes mediante la configuración de precios preferenciales',
    SUBTITULOGIN: 'LOGIN',
    SUBTITULOPERFIL: 'Queremos que tu experiencia sea la mejor',
    SUBTITULOADMINISTRADOR: 'ADMINISTRADOR',
    TITULOCONVENIODEPAGO:'CONVENIO DE PAGO',
    TITULOCONVENIODERECAUDO:'CONVENIO DE RECAUDO',
    TITULOSERVICIOSFINANCIEROS:'SERVICIOS FINANCIEROS',
    TITULODEPOSITOSALAVISTA:'DEPÓSITOS A LA VISTA',
    PARRAFOENCABEZADOPRINCIPAL:'Digita el ID del cliente para consultarlo. Puedes ingresar la informacion en caso de clientes nuevos o actualizarla en clientes actuales. Adicionalmente puedes iniciar una solicitud de precio preferencial.',
    TITULOENCABEZADOPRINCIPAL:'MENÚ',
    SUBTITULOENCABEZADOPRINCIPAL:'Principal',
    TITULOCONVENIOSYSERVICIOS:'CONVENIOS',
    SUBTITULOCONVENIOSYSERVICIOS:'y Servicios',
    TITULODEPOSITOSALAVISTAENC:'DEPÓSITOS',
    SUBTITULODEPOSITOSALAVISTA:'a la vista',
    TITULORESUMENDELAOPERACION:'RESUMEN',
    SUBTITULORESUMENDELAOPERACION:'de la operación',
    TITULOMENUSOLICITUD:'MENÚ',
    SUBTITULOMENUSOLICITUD:'Solicitud',
    PARRAFOMENUSOLICITUD:'Selecciona el tipo de producto y el tipo de operación que incluye la solicitud de precio preferencial. Pudes elegir un solo tipo de producto y operación o realizar varios en la misma solicitud',
    TITULOCONFIGURACION:'CONFIGURACIÓN',
    SUBTITULOCONFIGURACION:'Documentos de convenio',
    TITULOCARGUEDOCUMENTOS:'CARGUE',
    SUBTITULOCARGUEDOCUMENTOS:'Documentos',
    TITULOBANDEJA:'BANDEJA',
    SUBTITULOBANDEJA:'Solicitudes Activas',
    TITULOTABLAREMI:'TABLA',
    SUBTITULOTABLAREMI:'Remi',
})
export { USER_SMS_STATUS };