apiVersion: v1
data:
  usuario_aurora: YWRtaW4=
  password_aurora: QVhCU3NBVFZKSTVLdWx0dzQxUTY=
  url_aurora: YXBiYW5jYWVtcC1pbnN0YW5jZS0xLmN0cXVldDJkZ3B1cy51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  puerto_despliegue: ODA4MA==
  squema_aurora: TU9ERUxPX0RBVE9TX05VQkU=
  nombre_bd_aurora: T1JJR0lOQURPUl9EQg==
  puerto_bd_aurora: MzMwNg==
  #AUTH APP
  auth_app: JFM0NDQzNDIzNDNBU1NEQURTRFNEUzEzMjEyMS4uMzU0Lg==
  #AUTH SERVICIOS
  auth_cognito_usu: MnViZ2ZyMWk0Z2F0ZXN1djRkMzZmamhkdHY=
  auth_cognito_pass: MThicmwycWttOGhmaDRwdWtjczBzNHRtbzBxb2phN3RvYWRzaTA0OW9xZm9wZGpyMGQ1aQ==
  #EMAIL
  url_mail: ZW1haWwtc210cC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbQ==
  puerto_mail: MjU4Nw==
  ssl_tls_mail: MA==
  usuario_mail: QUtJQVpBRkM3TzZSNFhNTVFJNzY=
  password_mail: Qk41UVRqS0xGL1pJUzY5YmVnMEs0WDhXUE9rZFZjVEtRTVZGWXg1aDE0bm0=
  #URL APP
  url_aplicacion: aHR0cHM6Ly9wcmljaW5nLXFhLmRldmJhbmNvb21ldmEuY28v
  #URL SERVICIOS
  url_knime: a25pbWVsYi5kZXZiYW5jb29tZXZhLmNv
  puerto_knime: ""
  path_knime: L2tuaW1lL3Jlc3QvdjQvcmVwb3NpdG9yeS9RQS93YW50bmdldC9wcmljaW5nX3YyOmpvYi1wb29s
  url_cognito: cHJvdmVlZG9yZXMuYXV0aC51cy1lYXN0LTEuYW1hem9uY29nbml0by5jb20=
  path_cognito: L29hdXRoMi90b2tlbj9ncmFudF90eXBlPWNsaWVudF9jcmVkZW50aWFscw==
  url_profile: N2R6NGx4ajgwZi5leGVjdXRlLWFwaS51cy1lYXN0LTEuYW1hem9uYXdzLmNvbQ==
  puerto_profile: ""
  path_profile: L1FBL21lZGlhY2lvbndzYWMvdmFsaWRhdGV1c2Vy
  url_cliente: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  puerto_cliente: NDQz
  path_cliente: L2J1Yy9hcGkvdjEvYnVjL2NvbnN1bHRhVW5pY2FEYXRvc0NsaWVudGU=
  url_catalogo: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  puerto_catalogo: ""
  path_catalogo: L1V0aWxpdGllc0FkbWluL2FwaS92My9DYXRhbG9nL0dldA==
  url_inspektor: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  puerto_inspektor: NDQz
  path_inspektor: L1BhcnR5UmVmZXJlbmNlL2FwaS92My9SZXN0cmljdGVkL1JldHJpZXZl
  url_crear_participantes_pj: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  puerto_crear_participantes_pj: NDQz
  path_crear_participantes_pj: L2J1Yy9hcGkvdjEvYnVjL2NyZWFyTW9kaWZpY2FyQ2xpZW50ZVBqcA==
  url_crear_participantes_pn: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  puerto_crear_participantes_pn: NDQz
  path_crear_participantes_pn: L2J1Yy9hcGkvdjEvYnVjL2NyZWFyTW9kaWZpY2FyQ2xpZW50ZVBucA==
  url_crear_cliente_pj: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  puerto_crear_cliente_pj: NDQz
  path_crear_cliente_pj: L2J1Yy9hcGkvdjEvYnVjL2NyZWFyTW9kaWZpY2FyQ2xpZW50ZVBq
  #KEYCLOAK
  host_keycloak_token: a2V5Y2xvYWtxYS5iYW5jb29tZXZhLmNvbS5jbw==
  port_keycloak_token: ""
  path_keycloak_token: L3JlYWxtcy9xYS1iYW5jb29tZXZhL3Byb3RvY29sL29wZW5pZC1jb25uZWN0L3Rva2Vu
  keycloak_grant_type: Y2xpZW50X2NyZWRlbnRpYWxz
  keycloak_cliente_id: VGVzdENsaWVudFFB
  keycloak_cliente_secret: UkpKZHJMMHFJNWdWdzhLeWdOVkFuQzVuWldvYmlSQTk=
  #TIMEDOUT
  timedout_sesiones: ODA=
  timedout_servicios: MTAwMDA=
  timedout_knime: NjAwMDA=
  #SESSION INACTIVITY
  inactivity_time: MzA= 
  modal_display_time: MzA=
  session_expiration_time: MzA=
  #BUCKET_S3
  region_aws: dXMtZWFzdC0x
  nombre_bucket: cHJpY2luZ2FwcHJlY2lvcw==
  access_key_bucket: QUtJQVpBRkM3TzZSV01IQ1ZNRkU=
  secret_access_bucket: OWtmQWtLckQxRHJRT24wWW9ybGNYODAwaXo3bTIwQkNRZ3A2TW8wZQ==
  path_bucket: Q29udmVuaW9zL1FBL0RvY3VtZW50b3NSYWRpY2Fkb3M=
  # Crear Producto Captacion Cuentas Maestras
  url_productoCaptacion: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  url_port_productoCaptacion: NDQz
  url_path_productoCaptacion: L0RlcG9zaXRBY2NvdW50TWdtdC9hcGkvdjMvQ2FwdGEvSW5pdGlhdGU=
  # Consultar Cuentas
  url_host_cuentaSobregiro: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  url_port_cuentaSobregiro: NDQz
  url_path_cuentaSobregiro: L1NhdmluZ3NBY2NvdW50L2FwaS92My9SZXRyaWV2ZQ==
  # Asignar Sobregiros
  url_host_asignarSobregiro: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  url_port_asignarSobregiro: NDQz
  url_path_asignarSobregiro: L0N1cnJlbnRBY2NvdW50L2FwaS92My9PdmVyZHJhZnQvSW5pdGlhdGU=
  # Crear PAP
  url_host_crearPAP: d2ViYXBwc2Rldi5kZXZiYW5jb29tZXZhLmNv
  url_port_crearPAP: NDQz
  url_path_crearPAP: L1Rlcm1EZXBvc2l0L2FwaS92My9QQVAvSW5pdGlhdGU=
  ##Enviar Correo
  url_host_enviarCorreo: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  url_port_enviarCorreo: NDQz
  url_path_enviarCorreo: L1V0aWxpdGllc0FkbWluL2FwaS92My9FbWFpbC9TZW5k
  ##Consultar Fecha de Corte
  url_host_queryCorte: d2ViYXBwc2Rldi5kZXZiYW5jb29tZXZhLmNv
  url_port_queryCorte: NDQz
  url_path_queryCorte: L2N1c3RvbWVyQmlsbGluZy9hcGkvdjIvcmV0cmlldmVOZXh0QmlsbGluZ0N5Y2xl
  ##Consultar Deposito a Plazo
  url_host_queryDepositoPlazo: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  url_port_queryDepositoPlazo: NDQz
  url_path_queryDepositoPlazo: L1Rlcm1EZXBvc2l0L2FwaS92My9SZXRyaWV2ZQ==
  ##Simular Deposito a Plazo
  url_host_simularDepositoPlazo: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  url_port_simularDepositoPlazo: NDQz
  url_path_simularDepositoPlazo: L1Rlcm1EZXBvc2l0L2FwaS92My9DRFQvU2ltdWxhdGU=
  ##Crear CDT
  url_host_crearCdt: d2ViYXBwc3BydWViYXMuZGV2YmFuY29vbWV2YS5jbw==
  url_port_crearCdt: NDQz
  url_path_crearCdt: L1Rlcm1EZXBvc2l0L2FwaS92My9DRFRDREFUL0luaXRpYXRl
  ##Canonicals-header
  orinatingBank: QmFuY29vbWV2YQ==
  callBackUrl: aHR0cHM6Ly9hcGkuYmFuY29vbWV2YS5jb20vY2FsbGJhY2s=
  channel: MA==
  ##Canonicals-metadata
  priority: aGlnaA==
  serviceLevelAgreement: c3RhbmRhcmQ=
  processingMode: YXN5bmNocm9ub3Vz
  ##Canonicals-clientApp
  appName: WFBFUlQgQlVTSU5FU1M=
  appVersion: MS4xLjI4
  # activar certificado
  certificado_ssl: MA==
kind: Secret
metadata:
  name: apbancaemp-db-secret
  namespace: banca-comercial
type: Opaque
