apiVersion: v1
kind: Secret
metadata:
  name: apbancaemp-secret
  namespace: banca-comercial
type: Opaque
data:
  #DB
  usuario_aurora: 
  password_aurora: 
  url_aurora: YXBiYW5jYWVtcC1pbnN0YW5jZS0xLmN0cXVldDJkZ3B1cy51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  squema_aurora: TU9ERUxPX0RBVE9TX05VQkU=
  nombre_bd_aurora: T1JJR0lOQURPUl9EQg==
  puerto_bd_aurora: MzMwNg==
  #AUTH APP
  auth_app: 
  #AUTH COGNITO
  auth_cognito_usu: 
  auth_cognito_pass: 
  #CREDETIAL EMAIL
  usuario_mail: 
  password_mail: 
  #AUTH KEYCLOAK 
  keycloak_grant_type: 
  keycloak_cliente_id: 
  keycloak_cliente_secret: 
  #BUCKET_S3
  access_key_bucket: 
  secret_access_bucket: 