insert into estado_aso (COD_ESTADO_ASO, ESTADO_ASO)
value(0, 'Estado de Asociado'),
(9, 'No Estado'),                                                                       
(10, 'Activo Normal'),                                                            
(11, 'Activo Cobranza Interna'),                                                  
(12,'Activo, Pre-Vinculado'),   
(13, 'Activo Cobranza Prejuridico Externo'),     
(14, 'Inactivo'),                                 
(15, 'Activo No Cobranza Secuestrado'),                                                 
(17, 'Receso'),
(18, 'Juridico Sin Proceso'),
(20, 'Suspendido Normal'),
(21, 'Suspendido Cobranza Interna'),
(22, 'Suspendido Cobranza Prejuridico Interno'),
(23, 'Suspendido Fidelización por Crédito'),
(24, 'Suspendido por Terminación Tiempo Inactivo'),
(25, 'Suspendido Cobranza Castigado'),                               
(26, 'Suspendido por Fallecimiento'),
(27, 'Suspendido - Receso'),
(30, 'Retirado Normal'),                       
(31, 'Retirado Cobranza Interna'),
(32, 'Retirado Cobranza Prejuridico Interno'),
(33, 'Retirado Cobranza Prejuridico Externo'),
(34, 'Retirado Cobranza Juridico'),
(35, 'Retirado Cobranza Castigado'),
(36, 'Retirado Cobranza Castigado Normalizado'),
(37, 'Retirado - Receso'),                                  
(40, 'Excluido Normal'),                      
(41, 'Excluido Cobranza Interna'),                   
(42, 'Excluido Cobranza Prejuridico Interno'),
(43, 'Excluido Cobranza Prejuridico Externo'),
(44, 'Excluido Cobranza Juridico'),                   
(45, 'Excluido Cobranza Castigado'),
(46, 'Excluido Cobranza Castigado Normalizado'),
(47, 'Excluido Normalizado'),
(48, 'Expulsión de la Cooperativa'),
(50, 'Fallecido Normal'),
(51, 'Fallecido Cobranza Cobranza Interna'),          
(52, 'Fallecido Cobranza Prejuridico Interno'),
(53, 'Fallecido Cobranza Prejuridico Externo'),
(54, 'Fallecido Cobranza Juridico'), 
(55, 'Fallecido Cobranza Castigado'),
(56, 'Fallecido Cobranza Normalizado'),
(99, 'Retiro Administrativo BUC');