-- stored procedure loginUser v1
DELIMITER $$
	CREATE PROCEDURE queryLoginUsuario (IN LOGIN VARCHAR(45))
		BEGIN
			SELECT USU.USUARIO, USU.CORREO, PER.PERFIL, PRU.COD_PERFIL, USU.COD_PERF_CLIENTE
			FROM usuario AS USU
			JOIN perfiles_usuario AS PRU ON USU.USUARIO = PRU.USUARIO
			JOIN perfiles AS PER ON PRU.COD_PERFIL = PER.COD_PERFIL
			WHERE USU.USUARIO = LOGIN;
		END$$
DELIMITER ;
DROP PROCEDURE queryLoginUsuario;
CALL queryLoginUsuario(?);