DELIMITER $$
	DROP PROCEDURE IF EXISTS insertUsuario;
	CREATE PROCEDURE insertUsuario (IN USU VARCHAR(15), NOM VARCHAR(80), COR VARCHAR(80), CAR INT, OFI INT, REG INT, CAN INT, PCLI INT, PPRO VARCHAR(100))
		BEGIN
			INSERT INTO usuario ( USUARIO, NOMBRE, CORREO, COD_CARGO, COD_OFICINA, COD_REGIONAL, COD_CANAL, COD_PERF_CLIENTE, COD_PERF_PRODUCTO)
			VALUES(USU, NOM, COR, CAR, OFI, REG, CAN, PCLI, PPRO);
		END$$
DELIMITER ;

CALL insertUsuario(?, ?, ?, ?, ?, ?, ?, ?, ?);