-- stored procedure queryListarCreditos
DELIMITER $$
	CREATE PROCEDURE queryListarCreditos(IN NIT CHAR(10))
		BEGIN			
            IF NIT is null THEN
				SELECT A.COD_SOLICITUD, A.NIT_CLIENTE,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.cliente') AS CLIENTE,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_EA') AS RENTABILIDAD,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_MINIMO') AS RENTABILIDAD_MIN,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.UTILIDAD_ANUAL') AS UTILIDAD_ANUAL,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_COSTO_INTEGRAL') AS COSTO_INTEGRAL,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.POR_COSTO_INTEGRAL_Max') AS COSTO_INTEGRAL_MAX,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.ENTE_ATRIBUCION_FINAL') AS ENTE_ATRIBUCION,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PARAMETRIZADOR') AS COD_PARAMETRIZADOR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoMonto') AS CUPO_MONTO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoMonto') AS TESO_MONTO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoPlazo') AS CUPO_PLAZO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoPlazo') AS TESO_PLAZO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoIBR') AS CUPO_IBR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoIBR') AS TESO_IBR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoCobertura') AS CUPO_COBERTURA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoCobertura') AS TESO_COBERTURA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.promedio') AS RECIPROCIDAD,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_ENTE_ATRIBUCION_FINAL[0].tipo_aprobador') AS CARGO_APRO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_PARAMETRIZADOR.CARGO') AS CARGO_PARA,
				if(B.estadoAprobacion is null, 'En Proceso', if(B.estadoAprobacion = 1, 'Aprobado', 'No Aprobado')) AS Aprobacion,
				if(B.estadoAprobacion = 1, 'Asignado', if(B.estadoParametrizacion = 0, 'No Aprobado', if(B.estadoParametrizacion = 1, 'Aprobado', 'No Asignado'))) AS Parametrizacion
				FROM solicitudes AS A
				LEFT JOIN estado_solicitud AS B ON A.COD_SOLICITUD = codSolicitud
                ORDER BY COD_SOLICITUD ASC
                Limit 50;
            ELSE
				SELECT A.COD_SOLICITUD, A.NIT_CLIENTE,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.cliente') AS CLIENTE,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_EA') AS RENTABILIDAD,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_MINIMO') AS RENTABILIDAD_MIN,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.UTILIDAD_ANUAL') AS UTILIDAD_ANUAL,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_COSTO_INTEGRAL') AS COSTO_INTEGRAL,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.POR_COSTO_INTEGRAL_Max') AS COSTO_INTEGRAL_MAX,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.ENTE_ATRIBUCION_FINAL') AS ENTE_ATRIBUCION,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PARAMETRIZADOR') AS COD_PARAMETRIZADOR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoMonto') AS CUPO_MONTO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoMonto') AS TESO_MONTO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoPlazo') AS CUPO_PLAZO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoPlazo') AS TESO_PLAZO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoIBR') AS CUPO_IBR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoIBR') AS TESO_IBR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoCobertura') AS CUPO_COBERTURA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoCobertura') AS TESO_COBERTURA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.promedio') AS RECIPROCIDAD,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_ENTE_ATRIBUCION_FINAL[0].tipo_aprobador') AS CARGO_APRO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_PARAMETRIZADOR.CARGO') AS CARGO_PARA,
				if(B.estadoAprobacion is null, 'En Proceso', if(B.estadoAprobacion = 1, 'Aprobado', 'No Aprobado')) AS Aprobacion,
				if(B.estadoAprobacion = 1, 'Asignado', if(B.estadoParametrizacion = 0, 'No Aprobado', if(B.estadoParametrizacion = 1, 'Aprobado', 'No Asignado'))) AS Parametrizacion
				FROM solicitudes AS A
				LEFT JOIN estado_solicitud AS B ON A.COD_SOLICITUD = codSolicitud
				WHERE A.NIT_CLIENTE = NIT
				ORDER BY COD_SOLICITUD ASC;
            END IF;
		END$$
DELIMITER ;

DROP PROCEDURE queryListarCreditos;
CALL queryListarCreditos(?);
CALL queryListarCreditos('');