-- stored procedure queryDatosCorreo
DELIMITER $$
	CREATE PROCEDURE queryDatosCorreo(IN SOLICITUD INT, CORREOS TEXT)
		BEGIN
			SELECT 1 AS COD, A.COD_SOLICITUD, A.NIT_CLIENTE,
			JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.cliente') AS CLIENTE,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.antiguedad_ban') AS ANTIGUEDAD, 
			(CORREOS) AS CORREO,
            (SELECT REGIONAL_RAD FROM regional WHERE COD_REGIONAL_RAD = CONVERT(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.regional'),SIGNED)) AS REGIONAL,
			JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_EA') AS RENTABILIDAD,
			JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_MINIMO') AS RENTABILIDAD_MIN,
			JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.UTILIDAD_ANUAL') AS UTILIDAD_ANUAL,
			JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_COSTO_INTEGRAL') AS COSTO_INTEGRAL,
			JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.POR_COSTO_INTEGRAL_Max') AS COSTO_INTEGRAL_MAX,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.TOTAL_PROMEDIO_COLOCA') AS TOTAL_CARTERA,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.VALOR_CAPTACION_1') AS TOTAL_CAPTACION,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.TOTAL_MARGEN_CARTERA') AS MARGEN_CARTERA,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.MARGEN_CAPTACION') AS MARGEN_CAPTACION,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.MARGEN_CONVENIOS') AS MARGEN_CONVENIOS,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.ADQUI_RECIPRO') AS RECIPROCIDAD_ADQUIRIDA,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_ENTE_ATRIBUCION_FINAL[0].tipo_aprobador') AS CARGO_APRO,
			JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_PARAMETRIZADOR.CARGO') AS CARGO_PARA,
            
			JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO[0].monto')) AS CUPO_MONTO,
			JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO[1].monto')) AS TESO_MONTO,
			JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO[0].plazo')) AS CUPO_PLAZO,
			JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO[1].plazo')) AS TESO_PLAZO,
			JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO[0].coberturaFng')) AS CUPO_COBERTURA,
			JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO[1].coberturaFng')) AS TESO_COBERTURA,
			JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO[0].spreadIbr')) AS CUPO_REDESCUENTO,
			JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO[1].spreadIbr')) AS TESO_REDESCUENTO,
            
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RECIPROCIDAD_RESUMEN.ahorro.monto1')AS AHORROMONTO,
			JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RECIPROCIDAD_RESUMEN.ahorro.tasa1')AS AHORROTASA,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RECIPROCIDAD_RESUMEN.corriente.monto0')AS CORRIENTEMONTO,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RECIPROCIDAD_RESUMEN.corriente.tasa0')AS CORRIENTETASA,
            
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.SOLICITUD.tipoProducto.credito')AS CREDITO,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.SOLICITUD.tipoProducto.convenio')AS CONVENIO,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.SOLICITUD.tipoOperacion.nuevo')AS OPERACION,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.SOLICITUD.tipoConvenio.convenioPago')AS CONVENIOPAGO,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.SOLICITUD.tipoConvenio.convenioRecaudo')AS CONVENIORECAUDO,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.SOLICITUD.tipoConvenio.servicioFinanciero')AS SERVICIOFINANCIERO,
            
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_PAGO.convenioPagoNominaTipo')AS CONVENIONOMINA,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_PAGO.convenioPagoTerceros')AS CONVENIOTERCEROS,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_RECAUDO.recaudoOficina')AS RECAUDOBARRAS,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_RECAUDO.recaudoOficina')AS RECAUDOREFERENCIA,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_RECAUDO.recaudoPSE')AS RECAUDOPSE,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_RECAUDO.recaudoPSE')AS RECAUDOPORTAL,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_RECAUDO.recaudoCorresponsales')AS RECAUDOCORRESPONSAL,
            JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_RECAUDO.adquirencia')AS RECAUDOADQUIRENCIA
			FROM solicitudes AS A
			WHERE A.COD_SOLICITUD = SOLICITUD;
		END$$
DELIMITER ;

DROP PROCEDURE queryDatosCorreo;
CALL queryDatosCorreo(?, ?);
CALL queryDatosCorreo(215, '22');
