DELIMITER $$
	CREATE PROCEDURE queryDetalleSolicitud(IN COD INT)
		BEGIN			
            	SELECT 
                A.COD_SOLICITUD,
                A.ID_RADICADOR,
                A.NIT_CLIENTE,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.PRODUCTO') AS PRODUCTO,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO') AS CREDITO_NUEVO,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_PAGO') AS CONVENIO_PAGO,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_RECAUDO') AS CONVENIO_RECAUDO,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONVENIO_SERVICIO') AS SERVICIOS_FINANCIEROS,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION') AS RADICACION,
                JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.DOCUMENTO')) AS DOCUMENTO,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.REMI') AS REMI,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.DEPOSITO_VISTA') AS DEPOSITO_VISTA,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RECIPROCIDAD_RESUMEN') AS RECIPROCIDAD_RESUMEN,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CONFIGURACIO') AS CONFIGURACION,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.TECNICO_OPERADOR') AS TECNICO_OPERADOR	,
                JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CLIENTE_MODAL')) AS CLIENTE_MODAL,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CAMPO_ADICIONALES_MODAL') AS CAMPO_ADICIONALES_MODAL,
                JSON_UNQUOTE(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CLIENTE_FIDUCIA')) AS CLIENTE_FIDUCIA,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.EDITAR') AS EDITAR,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.ESTADO_SOLICITUD') AS ESTADO_SOLICITUD,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.SOLICITUD') AS SOLICITUD,
                JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME') AS KNIME
				FROM solicitudes AS A
				WHERE A.COD_SOLICITUD = COD;
		END$$
DELIMITER ;

DROP PROCEDURE queryDetalleSolicitud;
CALL queryDetalleSolicitud(?);
CALL queryDetalleSolicitud(3);
