DELIMITER $$
	DROP PROCEDURE IF EXISTS updateUsuario;
	CREATE PROCEDURE updateUsuario (IN USU VARCHAR(15), CAR INT, OFI INT, REG INT, CAN INT, PCLI INT, PPRO VARCHAR(100))
		BEGIN
			UPDATE usuario AS U 
			SET U.COD_CARGO = CAR, U.COD_OFICINA = OFI, U.COD_REGIONAL = REG, U.COD_CANAL = CAN, COD_PERF_CLIENTE = PCLI, COD_PERF_PRODUCTO = PPRO
			WHERE U.USUARIO = USU;
		END$$
DELIMITER ;

CALL updateUsuario('RAD1', 2, 1801, 2, 2, 2);