-- stored procedure queryListarCreditoPorAprobacion
DELIMITER $$
	CREATE PROCEDURE queryListarCreditoPorAprobacion(IN COD CHAR(15), NIT CHAR(10))
		BEGIN			
            IF NIT = '' THEN
            SELECT A.COD_SOLICITUD, A.NIT_CLIENTE,
				(SELECT REGIONAL_RAD FROM regional WHERE COD_REGIONAL_RAD = CAST(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.regional') AS SIGNED)) AS REGIONAL,
				(SELECT OFICINA FROM oficina WHERE COD_OFICINA = CAST(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.oficina') AS SIGNED)) AS OFICINA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.cliente') AS CLIENTE,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_EA') AS RENTABILIDAD,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_MINIMO') AS RENTABILIDAD_MIN,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.UTILIDAD_ANUAL') AS UTILIDAD_ANUAL,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_COSTO_INTEGRAL') AS COSTO_INTEGRAL,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.POR_COSTO_INTEGRAL_Max') AS COSTO_INTEGRAL_MAX,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.ENTE_ATRIBUCION_FINAL') AS ENTE_ATRIBUCION,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PARAMETRIZADOR') AS COD_PARAMETRIZADOR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoMonto') AS CUPO_MONTO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoMonto') AS TESO_MONTO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoPlazo') AS CUPO_PLAZO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoPlazo') AS TESO_PLAZO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoIBR') AS CUPO_IBR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoIBR') AS TESO_IBR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoCobertura') AS CUPO_COBERTURA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoCobertura') AS TESO_COBERTURA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.promedio') AS RECIPROCIDAD,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_ENTE_ATRIBUCION_FINAL[0].tipo_aprobador') AS CARGO_APRO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_PARAMETRIZADOR.CARGO') AS CARGO_PARA,
				B.idasignacion, B.codEnte, C.codDecision, A.APROREQUERIDAS
				FROM solicitudes AS A
				JOIN asignaciones AS B ON A.COD_SOLICITUD = B.codSolicitud 
				LEFT JOIN estado_asignacion AS C ON B.idasignacion = C.idasignacion
				WHERE isnull(C.codDecision) AND B.codEnte = COD AND B.codTipo != 0
				ORDER BY COD_SOLICITUD ASC;
            ELSE
				SELECT A.COD_SOLICITUD, A.NIT_CLIENTE,
				(SELECT REGIONAL_RAD FROM regional WHERE COD_REGIONAL_RAD = CAST(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.regional') AS SIGNED)) AS REGIONAL,
				(SELECT OFICINA FROM oficina WHERE COD_OFICINA = CAST(JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.oficina') AS SIGNED)) AS OFICINA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.RADICACION.cliente') AS CLIENTE,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_EA') AS RENTABILIDAD,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_ROA_MINIMO') AS RENTABILIDAD_MIN,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.UTILIDAD_ANUAL') AS UTILIDAD_ANUAL,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PORC_COSTO_INTEGRAL') AS COSTO_INTEGRAL,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.POR_COSTO_INTEGRAL_Max') AS COSTO_INTEGRAL_MAX,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.ENTE_ATRIBUCION_FINAL') AS ENTE_ATRIBUCION,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.PARAMETRIZADOR') AS COD_PARAMETRIZADOR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoMonto') AS CUPO_MONTO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoMonto') AS TESO_MONTO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoPlazo') AS CUPO_PLAZO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoPlazo') AS TESO_PLAZO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoIBR') AS CUPO_IBR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoIBR') AS TESO_IBR,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.cupoCobertura') AS CUPO_COBERTURA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.tesoCobertura') AS TESO_COBERTURA,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.CREDITO_NUEVO.promedio') AS RECIPROCIDAD,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_ENTE_ATRIBUCION_FINAL[0].tipo_aprobador') AS CARGO_APRO,
				JSON_EXTRACT(A.DATOS_SOLICITUD,'$.KNIME.DATOS_PARAMETRIZADOR.CARGO') AS CARGO_PARA,
				B.idasignacion, B.codEnte, C.codDecision, A.APROREQUERIDAS
				FROM solicitudes AS A
				JOIN asignaciones AS B ON A.COD_SOLICITUD = B.codSolicitud 
				LEFT JOIN estado_asignacion AS C ON B.idasignacion = C.idasignacion
				WHERE isnull(C.codDecision) AND B.codEnte = COD AND A.NIT_CLIENTE = NIT AND B.codTipo != 0
				ORDER BY COD_SOLICITUD ASC;
            END IF;
		END$$
DELIMITER ;

DROP PROCEDURE queryListarCreditoPorAprobacion;
CALL queryListarCreditoPorAprobacion(?);
CALL queryListarCreditoPorAprobacion('mapo1982', '');