DELIMITER $$
	DROP PROCEDURE IF EXISTS queryListarUsuario;
	CREATE PROCEDURE queryListarUsuario ()
		BEGIN
    		SELECT 
			A.USUARIO,
			A.NOMBRE,
			A.CORREO,
			A.COD_CARGO AS CARGO,
			A.COD_REGIONAL AS REGIONAL, 
            A.COD_OFICINA AS OFICINA,
			A.COD_CANAL AS CANAL,
			(SELECT json_arrayagg(J.COD_PERFIL)
				FROM perfiles_usuario AS H
				JOIN usuario AS I ON H.USUARIO = I.USUARIO
				JOIN perfiles AS J ON H.COD_PERFIL = J.COD_PERFIL
			WHERE H.USUARIO = A.USUARIO) AS PERFIL,
			B.COD_APROBADOR AS TIPO_APROBADOR,
            COD_PERF_CLIENTE AS PERFIL_CLIENTE,
            C.COD_PARAMETRIZADOR AS TIPO_PARAMETRIZADOR,
			A.COD_PERF_PRODUCTO AS PERFIL_PRODUCTO
			FROM usuario AS A
			LEFT JOIN ente_aprobacion AS B ON B.USUARIO = A.USUARIO
            LEFT JOIN ente_parametrizacion AS C ON C.USUARIO = A.USUARIO;
    	END$$
DELIMITER ;

CALL queryListarUsuario();